### ISSUE TITLE
Validation fired twice

### ISSUE THREAD

**Issue by brauliodiez** [ayosdev/ng-iban-custom#5]
I have been checking @unlooper  this issue, thay are using a summary control that counts the number of errors in the form, we have found that formatter is firing the validation and parsers as well, we have implemented a workaround, can we create a branch for this and ask for pull request?

Code update:

```
ctrl.$validators.ngIban = function(viewValue) {
          var parsed, valid;
          if (viewValue != null) {
            valid = isValidIban(viewValue);
            if (valid) {
              parsed = parseIban(viewValue);
              if (parsed !== viewValue) {
                ctrl.$setViewValue(parsed);
                ctrl.$render();
              }
            }
          }
    return valid;
        };
```

**Comment by Celestz** [comment]
Sure go ahead. We'll check it out when the PR arrives
On Apr 20, 2016 5:47 PM, "Braulio Diez" notifications@github.com wrote:

I have been checking @unlooper https://github.com/unlooper this issue,
thay are using a summary control that counts the number of errors in the
form, we have found that formatter is firing the validation and parsers as
well, we have implemented a workaround, can we create a branch for this and
ask for pull request?

Code update:

ctrl.$validators.ngIban = function(viewValue) {
var parsed, valid;
if (viewValue != null) {
valid = isValidIban(viewValue);
if (valid) {
parsed = parseIban(viewValue);
if (parsed !== viewValue) {
ctrl.$setViewValue(parsed);
ctrl.$render();
}
}
}
return valid;
};

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/ayosdev/ng-iban-custom/issues/5
